### ISSUE TITLE
nice  work 

### ISSUE THREAD

**Issue by huixiancheng** [wuwusky/lite_hrnet#2]
Thanks for the code.
could you show me the meaning of this code (which always use in the MMPose MMSeg or MMxxx)?

>     
       def train(self, mode=True):
        """Convert the model into training mode."""
        super().train(mode)
        if mode and self.norm_eval:
            for m in self.modules():
                if isinstance(m, _BatchNorm):
                    m.eval()

**Comment by wuwusky** [comment]
in my opinion，it works for frozening the parametes of 'batchnorm' to avoid the bias caused by the difference of data distribution

**Comment by huixiancheng** [comment]
thanks:bow:
