### ISSUE TITLE
None  in transition layers and fuse_layers??

### ISSUE THREAD

**Issue by huixiancheng** [wuwusky/lite_hrnet#3]
Look like None in  transition mean that none  downsample in this branch
None in fuse_layers mean Same Resolution Feature so don't need to adjust size in fuse_layers.
Is it right?
![QQ截图20210421232829](https://user-images.githubusercontent.com/65054204/115580026-4c901700-a2f9-11eb-93cb-4b53183f000e.png)
Moreover, this part look like should be delete.You also delete ShuffleUnit in your code since it's for naive hrnet .
https://github.com/wuwusky/lite_hrnet/blob/19bd01308437f5303d65bd8232ba3fe2f250b13f/model_hrnet.py#L283-L315

**Comment by huixiancheng** [comment]
话说，你用过这网络测试过吗，我用在分割上，64*1024的输入，把原始stem的4倍下采样改成了2倍，2080ti batch开6 显存有点吃不住，而且训练的latency也很大。

**Comment by wuwusky** [comment]
oh~~~,I just use it in condition " if self.module_type == 'LITE' ". so, ShuffleUnit is not used;
emmm, i have tested it as a backbone net, and it's performance is  worse than my older model, sad~~~

**Comment by huixiancheng** [comment]
How about the speed of convergence of your losses, in my experiments its convergence is very very slow. 
Look like there are tricks in experiment

**Comment by wuwusky** [comment]
emmm，the speed is really slower than my old backbone, and the parameters is really little (only ≈ 2M ).
The most important point is that performance down, sad~~
maybe, there are some tricks we didn't notice~~

**Comment by huixiancheng** [comment]
thx 🙇‍♂️
